### ISSUE TITLE
IPv6 remote_ip causing regexp error

### ISSUE THREAD

**Issue by pembo13** [rory/apache-log-parser#10]
Looks like the regexp for remote_ip is checking for IPv4 only `(?P<remote_ip>(?:\\d{1,3}\\.){3}\\d{1,3})` so this causes errors with IPv6 addresses

**Comment by rory** [comment]
Interesting. I've never really worked with IPv6 logs, but it's something that should be supported.

**Comment by pembo13** [comment]
Just to clarify, the site I encountered this in had both IPv4 and IPv6 bindings, so the log contained both types.

**Comment by rory** [comment]
Thanks for the bug report. I've released version 1.6 which fixes this. Can you let me know if it works?

**Comment by pembo13** [comment]
I'm using the following formatter:

    make_parser("%h %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"")

The following lines are not being parsed however:

    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:40:45 -0400] "GET /category/blog/page/3 HTTP/1.0" 200 41207 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:40:48 -0400] "GET /category/blog/page/9 HTTP/1.0" 200 33052 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:40:51 -0400] "GET /blog/ HTTP/1.0" 301 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:40:54 -0400] "GET /blog/page/4 HTTP/1.0" 200 41756 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:40:57 -0400] "GET /blog/page/5 HTTP/1.0" 200 42111 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:41:00 -0400] "GET /blog/page/8 HTTP/1.0" 200 41991 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:41:04 -0400] "GET /blog/page/7 HTTP/1.0" 200 42699 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"
    10.178.98.112 2607:5300:60:2c74:: - - [24/Mar/2015:16:41:07 -0400] "GET /category/article/page/2 HTTP/1.0" 200 39911 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30"

**Comment by uogbuji** [comment]
Just ran into this one, and have to monkeypatch in a hurry to fix. For anyone else stymied by it, just add this after your import:

```python
#Monkeypatch apache_log_parser to fix https://github.com/rory/apache-log-parser/issues/10
IPv6_ADDR_REGEX = r"([0-9A-Fa-f]{0,4}:){2,7}([0-9A-Fa-f]{0,4})"
#IPv6_ADDR_REGEX = r"(?:[\d\.]|[\da-fA-F:])+)" #If we need to get super-lax
IPv4_ADDR_REGEX, make_regex = apache_log_parser.IPv4_ADDR_REGEX, apache_log_parser.make_regex
IP_ADDR_REGEX = "("+IPv4_ADDR_REGEX+"|"+IPv6_ADDR_REGEX+")"
IP_ADDR_FORMAT = [make_regex('%a'), IP_ADDR_REGEX, lambda match: 'remote_ip', lambda matched_strings: matched_strings] #	Remote IP-address
apache_log_parser.FORMAT_STRINGS[1] = IP_ADDR_FORMAT
```

If I can I'll come back and prep a proper pull request, but for now I've got too many deadlines I'm scrambling to meet. Thanks for the project!

**Comment by rory** [comment]
@uogbuji Thanks for your suggestion. I've incorporated it into the newly released v1.6.2., which successfully accepts @pembo13 's log files.

**Comment by uogbuji** [comment]
Sure @rory, but I'm not sure this fix has made it to the version on PyPI as of now? Oddly I see:

```
pip show apache-log-parser
Name: apache-log-parser
Version: 1.7.0
Summary: Parse lines from an apache log file
Home-page: UNKNOWN
Author: Rory McCann
Author-email: rory@technomancy.org
License: GPLv3+
Location: /home/uche/.local/pyenv/main/lib/python3.6/site-packages
Requires: user-agents, six
```

But PyPI still shows 1.6.2? In either case I would have expected the fix to be in place, but I still have to  monkeypatch.
